name: Sync Repository to GitLab

on:
  push:
    branches: [main]  # adapte selon ta branche principale

jobs:
  sync:
    runs-on: self-hosted  # utilise ton runner self-hosted Windows
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # nécessaire pour récupérer tout l'historique git
    - name: Sync to GitLab
      uses: keninkujovic/gitlab-sync@2.1.0
      with:
        gitlab_url: ${{ secrets.GITLAB_URL }}
        username: ${{ secrets.USERNAME }}
        gitlab_pat: ${{ secrets.GITLAB_PAT }}
        force_push: false  # à true si tu veux forcer l'écrasement sur GitLab