name: Sync Repository to GitLab

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Sync to GitLab via PowerShell
      shell: pwsh
      run: |
        $gitlab_url = "${{ secrets.GITLAB_URL }}"
        $username = "${{ secrets.USERNAME }}"
        $token = "${{ secrets.GITLAB_PAT }}"
        $branch = "${{ github.ref }}" -replace 'refs/heads/', ''

        git remote add gitlab https://$username:$token@${gitlab_url#https://}
        git push gitlab $branch
